In [45]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [46]:
import pickle

In [47]:
from sklearn import linear_model
from sklearn.neighbors import KNeighborsClassifier

In [48]:
filein = 'data/titanic_train.pk'
with open(filein, 'rb') as f:
    train_data = pickle.load(f)

filein = 'data/titanic_test.pk'
with open(filein, 'rb') as f:
    test_data = pickle.load(f)

In [49]:
train_data

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0           0       3    0  22.0      1      0   7.2500
1           1       1    1  38.0      1      0  71.2833
2           1       3    1  26.0      0      0   7.9250
3           1       1    1  35.0      1      0  53.1000
4           0       3    0  35.0      0      0   8.0500
..        ...     ...  ...   ...    ...    ...      ...
885         0       3    1  39.0      0      5  29.1250
886         0       2    0  27.0      0      0  13.0000
887         1       1    1  19.0      0      0  30.0000
889         1       1    0  26.0      0      0  30.0000
890         0       3    0  32.0      0      0   7.7500

[714 rows x 7 columns]

In [50]:
X_train = train_data.drop('Survived', axis=1)

In [51]:
X_train = X_train.values

In [52]:
X_train

array([[ 3.    ,  0.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 3.    ,  1.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 1.    ,  1.    , 19.    ,  0.    ,  0.    , 30.    ],
       [ 1.    ,  0.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 3.    ,  0.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [53]:
X_train.shape

(714, 6)

In [54]:
y_train = train_data.Survived

In [55]:
y_train = y_train.values

In [56]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,

In [57]:
X_test = test_data.values

In [62]:
X_test

array([[  3.    ,   0.    ,  34.5   ,   0.    ,   0.    ,   7.8292],
       [  3.    ,   1.    ,  47.    ,   1.    ,   0.    ,   7.    ],
       [  2.    ,   0.    ,  62.    ,   0.    ,   0.    ,   9.6875],
       ...,
       [  3.    ,   1.    ,  28.    ,   0.    ,   0.    ,   7.775 ],
       [  1.    ,   1.    ,  39.    ,   0.    ,   0.    , 108.9   ],
       [  3.    ,   0.    ,  38.5   ,   0.    ,   0.    ,   7.25  ]])

In [61]:
# KNN 

knn = KNeighborsClassifier(n_neighbors = 3)

knn.fit(X_train, y_train)
Y_pred = knn.predict(X_test)
acc_knn = round(knn.score(X_train, y_train) * 100, 2)

In [63]:
acc_knn

82.91

In [64]:
knn.score?

Signature: knn.score(X, y, sample_weight=None)
Docstring:
Return the mean accuracy on the given test data and labels.

In multi-label classification, this is the subset accuracy
which is a harsh metric since you require for each sample that
each label set be correctly predicted.

Parameters
----------
X : array-like of shape (n_samples, n_features)
    Test samples.

y : array-like of shape (n_samples,) or (n_samples, n_outputs)
    True labels for `X`.

sample_weight : array-like of shape (n_samples,), default=None
    Sample weights.

Returns
-------
score : float
    Mean accuracy of ``self.predict(X)`` wrt. `y`.
File:      ~/.virtualenvs/astrometria/lib/python3.8/site-packages/sklearn/base.py
Type:      method
